name: CTAProject
options:
    bundleIdPrefix: cta.project
targets:
  CTAProject:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: CTAProject
    scheme:
      testTargets:
        - CTAProjectTests
    preBuildScripts:
      - path: ./Scripts/before-compile.sh
        name: before-compile
        shell: "/bin/bash"

  CTAProjectTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources: CTAProjectTests
    dependencies:
      - target: CTAProject
    settings:
      INFOPLIST_FILE: CTAProject/Info.plist
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
      LD_RUNPATH_SEARCH_PATHS[sdk=macosx*]: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks"
  CTAProjectUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "13.0"
    sources: CTAProjectUITests
    dependencies:
      - target: CTAProject
